<NATURAL JOIN과 USING 구문을 이용한 쿼리를 두 개 생성하세요.>
1) 송강 교수가 강의하는 과목을 검색하세요.
SELECT A.PNAME, B.CNAME
    FROM PROFESSOR A, COURSE B
    WHERE A.PNO = B.PNO
    AND A.PNAME = '송강';

SELECT PNAME, CNAME
    FROM PROFESSOR
    NATURAL JOIN COURSE
    WHERE PNAME = '송강';
    
SELECT PNAME, CNAME
    FROM PROFESSOR
    JOIN COURSE USING(PNO)
    WHERE PNAME = '송강';
2) 학점이 2학점인 과목과 이를 강의하는 교수를 검색하세요.
SELECT CNAME, PNAME, ST_NUM
    FROM COURSE A, PROFESSOR B
    WHERE A.PNO = B.PNO
    AND A.ST_NUM = 2;

SELECT CNAME, PNAME, ST_NUM
    FROM COURSE 
    NATURAL JOIN PROFESSOR
    WHERE ST_NUM =2;
    
SELECT CNAME, PNAME, ST_NUM
    FROM COURSE 
    JOIN PROFESSOR USING (PNO)
    WHERE ST_NUM = 2;

3) 화학과 1학년 학생의 기말고사 성적을 검색하세요.
SELECT C.SNAME, D.RESULT, C.MAJOR
    FROM PROFESSOR A, COURSE B, STUDENT C, SCORE D
    WHERE A.PNO = B.PNO
    AND C.SNO = D.SNO
    AND B.CNO = D.CNO
    AND MAJOR = '화학'
    AND SYEAR = 1;

SELECT SNAME, RESULT, MAJOR
    FROM PROFESSOR
    JOIN COURSE USING (PNO)
    JOIN SCORE USING (CNO)
    JOIN STUDENT USING (SNO)
    WHERE MAJOR = '화학'
    AND SYEAR = 1;

4) 일반화학 과목의 기말고사 점수를 검색하세요.
SELECT B.CNAME ,C.SNAME, D.RESULT, C.MAJOR
    FROM PROFESSOR A, COURSE B, STUDENT C, SCORE D
    WHERE A.PNO = B.PNO
    AND C.SNO = D.SNO
    AND B.CNO = D.CNO
    AND CNAME = '일반화학1';


SELECT CNAME, SNAME, RESULT, MAJOR
    FROM PROFESSOR
    JOIN COURSE USING (PNO)
    JOIN SCORE USING (CNO)
    JOIN STUDENT USING (SNO)
    WHERE CNAME = '일반화학1';